### ISSUE TITLE
Browser sometimes no longer able to run with Smart App Control active

### ISSUE THREAD

**Issue by tsd** [NuclearDevelopers/Dichromate#19]
Hello, I have been using Dichromate with the latest Windows 11 and Smart App Control activated for the past week without an issue, however the app is now blocked to run for me. Smart App Control is a novel feature that blocks [apps that are both unsigned and untrusted](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) by Microsoft's threat intelligence services. 

It is possible to fix this issue by signing the Dichromate app with a valid certificate or to have the user turn the feature off, which you cannot turn on again without resetting or reinstalling Windows.
 
 Since the feature isn't used by a lot of users I don't expect a quick fix, but just creating this issue so it's noted for other users.
 
![image](https://user-images.githubusercontent.com/70513548/220601512-8cba6f66-46c4-4622-9bb2-90aa7a39ef7d.png)

**Comment by Douloureux** [comment]
Sorry for the inconvenience. Although signing the program with a valid certificate would be great, obtaining a valid code signing certificate costs money, and for a small hobbyist project like this, it's not really worth it.  

I do have some alternatives to Smart App Control though. You can check out [AppLocker](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/applocker-overview) and [WDAC](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/wdac-and-applocker-overview#windows-defender-application-control), the former being easier to use than the latter. 

I will get back to this if I am able to get my hands on a signing certificate in the future.

**Comment by tsd** [comment]
Hey again,
It works again after the update deployed. I'd still keep this issue open as these alerts will likely appear again, unsure what causes Dichromate to flag in MSFT's cloud services.

I've also checked out these other features - I imagine they'd be better for some people but I'll be keeping SAC on for my configuration due to my own constraints. 

I understand the inability to get a real signing certificate but I am not too fussed since my approach is a little on the extreme.
